---

- name: backup script
  copy:
    src: files/backup_influxdb.sh
    dest: /home/pi
    owner: pi
    group: pi

- name: cron job
  cron:
    job: "/home/pi/backup_influxdb.sh {{ influxdb_backup_aws_profile }} {{ influxdb_backup_s3_bucket }} > /home/pi/influx_backup.log 2>&1"
    hour: '23'

